name: Build LIM Docs
on: push
jobs:
  buildDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.14.0.3'
      - run: pandoc -v       
      - name: Build everything
        run: ant -f ${{ github.workspace }}/build.xml documentation
      - name: Deploy documentation
        if: ${{ github.repository_owner == 'sfu-dhil' }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: public
          single-commit: true
                             