name: Build LIM Framework
on: push
jobs:
  buildFramework:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Framework
        run: ant -f {{ github.workspace }}/build.xml framework
      - name: Get version
        run: echo "VERSION=`cat ${{ github.workspace }}/VERSION`" >> $GITHUB_ENV
      - name: Release framework
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true